<a href="https://colab.research.google.com/github/divyashree91003-ai/Sentiment-Analysis-of-Amazon-Product-Reviews/blob/main/sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving amazonreviews.tsv to amazonreviews.tsv

In [2]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [3]:
nlp(u'lion').vector

array([-0.37331197, -0.636077  ,  0.16624087, -0.4500625 ,  0.02346338,
       -0.03507689,  1.2888179 ,  0.5569869 ,  0.00782521,  0.03196311,
        0.53636825, -0.53003603, -0.5546204 ,  0.07603534, -0.6676563 ,
        0.64938223, -0.57278097, -0.42561203,  0.78977346,  0.23432143,
       -0.4744925 ,  1.4517382 , -0.6984429 ,  0.17191873,  0.57576656,
        0.8409606 ,  0.5306976 , -0.16426727, -0.31692672,  1.1624684 ,
       -0.02932239,  0.6820288 , -0.09631193,  0.4340958 , -0.7869414 ,
       -0.67758393,  0.15711513,  0.77149993, -0.42237112,  0.43566388,
       -0.48777014,  0.05853128,  0.10582243,  0.6809435 ,  0.2115672 ,
        0.31190214, -0.5367352 , -0.71792245, -0.7814528 , -0.5595007 ,
       -0.06030444, -0.235009  ,  0.14786157, -0.9114496 , -0.04370221,
        0.33902794,  1.3769817 ,  0.03151399, -0.01746303,  0.17750838,
       -0.8129017 , -0.08208682, -0.45948845, -0.25383136, -0.22368991,
        0.00536951,  0.355986  , -0.08492555, -1.2826453 , -0.31713837,
       -0.05259013,  0.72026825,  0.06919017,  0.86950725, -0.32498598,
       -0.7104281 , -0.2691805 , -0.86355877,  0.01898009,  0.47686198,
       -0.25541353, -0.32858473, -0.72884005,  0.10324007, -0.5523401 ,
        0.44613484,  0.12074314,  0.4141845 , -0.6831957 ,  0.53131336,
       -1.0593603 ,  0.40895098,  0.9865373 , -0.13632178,  0.66824126,
        0.50666654], dtype=float32)

In [4]:
doc = nlp(u'The quick brown fox jumps over the lazy dog')
doc.vector

array([ 0.51749516, -0.39298344,  0.06351386,  0.3179498 , -0.3357426 ,
       -0.06497418,  0.02762074, -0.05084468,  0.11424626, -0.08697442,
       -0.16755731,  0.51097226,  0.0812857 , -0.11303581, -0.20498069,
        0.12366276, -0.25266135,  0.30896392, -0.17489922,  0.05506786,
       -0.30337694,  0.13884214, -0.03051401, -0.48852333,  0.23817785,
       -0.3130759 ,  0.00377634, -0.06416796,  0.40714777,  0.04062888,
        0.05956797, -0.46511665, -0.14377208, -0.21850671, -0.22041453,
       -0.07647462,  0.10079499,  0.24725853, -0.04442219, -0.10161617,
        0.17255768,  0.5498523 , -0.18680057,  0.02200245,  0.15186316,
       -0.00201839, -0.06265394,  0.47759995, -0.11117671,  0.18827844,
       -0.14982331,  0.39464778, -0.01036556,  0.04449752, -0.55395633,
        0.77604675, -0.05661564,  0.40694597, -0.35068357,  0.18003678,
       -0.27000117, -0.02612866, -0.2845863 , -0.5837178 , -0.2732299 ,
       -0.27385405,  0.2943883 , -0.19240773, -0.21924357, -0.26369688,
        0.1057464 ,  0.30174387,  0.3255409 ,  0.09667431, -0.02304691,
       -0.4366628 , -0.03649611, -0.6406051 ,  0.51604867, -0.38510653,
       -0.21193416,  0.02095865, -0.28476965, -0.00215156, -0.26570633,
        0.3295838 ,  0.5582533 , -0.35284424, -0.13938117,  0.34983155,
       -0.01497399,  0.3379818 ,  0.48265022,  0.35069853, -0.35370854,
       -0.2979136 ], dtype=float32)

In [7]:
tokens = nlp(u'lion cat pet')
for token1 in tokens:
  for token2 in tokens:
    print(token1.text,token2.text,token1.similarity(token2))

lion lion 1.0
lion cat 0.7044516205787659
lion pet 0.3186751902103424
cat lion 0.7044516205787659
cat cat 1.0
cat pet 0.36159902811050415
pet lion 0.3186751902103424
pet cat 0.36159902811050415
pet pet 1.0

/tmp/ipykernel_6325/3819551103.py:4: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text,token2.text,token1.similarity(token2))

In [8]:
tokens = nlp(u"love like hate")
for token1 in tokens:
  for token2 in tokens:
    print(token1.text,token2.text,token1.similarity(token2))

love love 1.0
love like 0.22832468152046204
love hate 0.3089393377304077
like love 0.22832468152046204
like like 1.0
like hate 0.17319534718990326
hate love 0.3089393377304077
hate like 0.17319534718990326
hate hate 1.0

/tmp/ipykernel_6325/3788697269.py:4: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text,token2.text,token1.similarity(token2))

In [9]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

True

In [10]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

In [11]:
a = 'This is very awesome movie'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.477, 'pos': 0.523, 'compound': 0.659}

In [12]:
a = 'This was the best, most awesome movie EVER MADE!'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.441, 'pos': 0.559, 'compound': 0.8716}

In [13]:
import numpy as np
import pandas as pd

In [16]:
df =pd.read_csv("amazonreviews.tsv",sep ="\t")

In [17]:
df.head()

  label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [18]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [19]:
df.dropna(inplace=True)
blanks=[]
for i,lb,rv in df.itertuples():
  if type(rv)==str:
    if rv.isspace():
      blanks.append(i)
print(len(blanks),'blanks: ',blanks)

0 blanks:  []

In [20]:
sid.polarity_scores(df.loc[0]['review'])

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [21]:
df['score']=df['review'].apply(lambda review:sid.polarity_scores(review))

In [22]:
df.head()

,label,review,score
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co..."
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co..."
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com..."
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com..."
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp..."

In [23]:
df['compound'] = df['score'].apply(lambda score_dict:score_dict['compound'])

In [24]:
df.head()

,label,review,score,compound
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...",0.9454
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...",0.8957
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...",0.9858
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...",0.9814
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...",0.9781

In [33]:
df['comp_score'] = df['compound'].apply(
    lambda c: '*****' if c >= 0.8 else ('***' if c >= 0.5 else '*')
)

In [34]:
df['comp_score1'] = df['compound'].apply(lambda c: 'pos' if c>=0 else 'neg')

In [35]:
df.head(50)

,label,review,score,compound,comp_score,comp_score1
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...",0.9454,*****,pos
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...",0.8957,*****,pos
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...",0.9858,*****,pos
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...",0.9814,*****,pos
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...",0.9781,*****,pos
5,pos,an absolute masterpiece: I am quite sure any o...,"{'neg': 0.014, 'neu': 0.737, 'pos': 0.249, 'co...",0.9900,*****,pos
6,neg,"Buyer beware: This is a self-published book, a...","{'neg': 0.124, 'neu': 0.806, 'pos': 0.069, 'co...",-0.8744,*,neg
7,pos,Glorious story: I loved Whisper of the wicked ...,"{'neg': 0.072, 'neu': 0.583, 'pos': 0.346, 'co...",0.9900,*****,pos
8,pos,A FIVE STAR BOOK: I just finished reading Whis...,"{'neg': 0.113, 'neu': 0.712, 'pos': 0.174, 'co...",0.8353,*****,pos
9,pos,Whispers of the Wicked Saints: This was a easy...,"{'neg': 0.033, 'neu': 0.777, 'pos': 0.19, 'com...",0.8196,*****,pos
10,neg,The Worst!: A complete waste of time. Typograp...,"{'neg': 0.36, 'neu': 0.586, 'pos': 0.054, 'com...",-0.9274,*,neg
11,pos,"Great book: This was a great book,I just could...","{'neg': 0.0, 'neu': 0.836, 'pos': 0.164, 'comp...",0.9538,*****,pos
12,pos,"Great Read: I thought this book was brilliant,...","{'neg': 0.044, 'neu': 0.554, 'pos': 0.402, 'co...",0.9850,*****,pos
13,neg,Oh please: I guess you have to be a romance no...,"{'neg': 0.077, 'neu': 0.723, 'pos': 0.199, 'co...",0.9097,*****,pos
14,neg,Awful beyond belief!: I feel I have to write t...,"{'neg': 0.171, 'neu': 0.755, 'pos': 0.074, 'co...",-0.9312,*,neg
15,neg,Don't try to fool us with fake reviews.: It's ...,"{'neg': 0.105, 'neu': 0.832, 'pos': 0.063, 'co...",-0.5414,*,neg
16,pos,A romantic zen baseball comedy: When you hear ...,"{'neg': 0.021, 'neu': 0.818, 'pos': 0.161, 'co...",0.9454,*****,pos
17,pos,Fashionable Compression Stockings!: After I ha...,"{'neg': 0.11, 'neu': 0.754, 'pos': 0.136, 'com...",0.5182,***,pos
18,pos,Jobst UltraSheer Thigh High: Excellent product...,"{'neg': 0.064, 'neu': 0.771, 'pos': 0.165, 'co...",0.7787,***,pos
19,neg,sizes recomended in the size chart are not rea...,"{'neg': 0.0, 'neu': 0.935, 'pos': 0.065, 'comp...",0.4926,*,pos
20,neg,mens ultrasheer: This model may be ok for sede...,"{'neg': 0.134, 'neu': 0.696, 'pos': 0.17, 'com...",0.6318,***,pos
21,pos,Delicious cookie mix: I thought it was funny t...,"{'neg': 0.044, 'neu': 0.809, 'pos': 0.147, 'co...",0.9517,*****,pos
22,neg,Another Abysmal Digital Copy: Rather than scra...,"{'neg': 0.037, 'neu': 0.819, 'pos': 0.145, 'co...",0.9667,*****,pos
23,pos,A fascinating insight into the life of modern ...,"{'neg': 0.0, 'neu': 0.81, 'pos': 0.19, 'compou...",0.9815,*****,pos
24,pos,i liked this album more then i thought i would...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.8979,*****,pos
25,neg,Problem with charging smaller AAAs: I have had...,"{'neg': 0.149, 'neu': 0.761, 'pos': 0.09, 'com...",-0.7845,*,neg
26,neg,"Works, but not as advertised: I bought one of ...","{'neg': 0.092, 'neu': 0.828, 'pos': 0.08, 'com...",-0.0857,*,neg
27,neg,"Disappointed: I read the reviews,made my purch...","{'neg': 0.085, 'neu': 0.915, 'pos': 0.0, 'comp...",-0.5017,*,neg
28,neg,Oh dear: I was excited to find a book ostensib...,"{'neg': 0.047, 'neu': 0.839, 'pos': 0.114, 'co...",0.6486,***,pos
29,pos,Based on the reviews here I bought one and I'm...,"{'neg': 0.058, 'neu': 0.815, 'pos': 0.127, 'co...",0.9176,*****,pos
30,neg,"Incorrect disc!: I am a big JVC fan, but I do ...","{'neg': 0.082, 'neu': 0.898, 'pos': 0.02, 'com...",-0.7433,*,neg
31,pos,happy with it...but: I'm a JVC nut...I have 3 ...,"{'neg': 0.0, 'neu': 0.917, 'pos': 0.083, 'comp...",0.9015,*****,pos
32,neg,"should be titled ""Hollywood Debacle"": The plot...","{'neg': 0.136, 'neu': 0.864, 'pos': 0.0, 'comp...",-0.8345,*,neg
33,pos,Is this great TV??? You bet it is: Hotel Babyl...,"{'neg': 0.009, 'neu': 0.79, 'pos': 0.201, 'com...",0.9896,*****,pos
34,neg,Nothing you don't already know: If you have ev...,"{'neg': 0.05, 'neu': 0.816, 'pos': 0.135, 'com...",0.4434,*,pos
35,neg,Unfortunately it wasn't entertaining in the le...,"{'neg': 0.094, 'neu': 0.732, 'pos': 0.174, 'co...",0.8513,*****,pos
36,pos,Rochelle explains It All for You: Wondering wh...,"{'neg': 0.08, 'neu': 0.774, 'pos': 0.147, 'com...",0.8219,*****,pos
37,pos,More great playing: Larry's work for the Muse ...,"{'neg': 0.0, 'neu': 0.688, 'pos': 0.312, 'comp...",0.9824,*****,pos
38,neg,Doesn't work on a Mac: It clearly says on line...,"{'neg': 0.0, 'neu': 0.892, 'pos': 0.108, 'comp...",0.5951,***,pos
39,neg,Very Frustrating: My three year old son was ve...,"{'neg': 0.092, 'neu': 0.812, 'pos': 0.096, 'co...",0.0892,*,pos
40,neg,Mind numbing: This game makes you do the same ...,"{'neg': 0.049, 'neu': 0.839, 'pos': 0.112, 'co...",0.6177,***,pos
41,neg,"Cannot recommend: As a former Alaskan, I didn'...","{'neg': 0.049, 'neu': 0.878, 'pos': 0.073, 'co...",0.7948,***,pos
42,pos,Alaska sourdough: REad most of the book while ...,"{'neg': 0.0, 'neu': 0.789, 'pos': 0.211, 'comp...",0.8402,*****,pos
43,pos,Old and good: This book is worth to keep in yo...,"{'neg': 0.051, 'neu': 0.888, 'pos': 0.062, 'co...",-0.1027,*,neg
44,pos,"autumn: got this for my daughter in NC, she is...","{'neg': 0.0, 'neu': 0.886, 'pos': 0.114, 'comp...",0.4019,*,pos
45,pos,Fast mp3 download of music waxed decades ago: ...,"{'neg': 0.0, 'neu': 0.897, 'pos': 0.103, 'comp...",0.7717,***,pos
46,neg,Maybe I got a bad one.: My experience: I got t...,"{'neg': 0.134, 'neu': 0.847, 'pos': 0.019, 'co...",-0.8688,*,neg
47,pos,"Sylvania 6620LDG 20"" Flat Panel LCD TV with Bu...","{'neg': 0.047, 'neu': 0.796, 'pos': 0.157, 'co...",0.9025,*****,pos
48,neg,TERRIBLE!! DO NOT BUY THIS: I bought this for ...,"{'neg': 0.167, 'neu': 0.833, 'pos': 0.0, 'comp...",-0.8405,*,neg
49,neg,*** BEWARE ***: This TV is set so that it is n...,"{'neg': 0.072, 'neu': 0.897, 'pos': 0.031, 'co...",-0.6226,*,neg

In [29]:
def star(compound):
  if compound>=0.8:
    return '*****'
  elif compound >=0.5:
    return '***'
  else:
    return '*'

In [30]:
from sklearn.metrics import classification_report, accuracy_score

In [36]:
accuracy_score(df['label'],df['comp_score1'])

0.7098

In [37]:
print(classification_report(df['label'],df['comp_score1']))

              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000